version: '3'
services:
  discovery-service:
#    build: discovery-server
    image: "lruchandani/discovery-server:${TAG}"
    ports:
      - "8761:8761"
  config-service:
#      build: config-service
      image : "lruchandani/config-service:${TAG}"
      ports:
        - "8888:8888"
      depends_on:
        - discovery-service
      command: ["./wait-for-it.sh","discovery-service:8761","-s","-t","300"]
      environment:
        server.port: 8888
        eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka
  book-service:
      image: "lruchandani/book-service:${TAG}"
      ports:
        - "8080:8080"
      depends_on:
        - discovery-service
        - config-service
      environment:
        eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka
        book.service.db.url: jdbc:mysql://172.29.177.161:3306/library?useSSL=false&allowPublicKeyRetrieval=true
  subscription-service:
      image: "lruchandani/subscription-service:${TAG}"
      ports:
        - "8081:8081"
      depends_on:
        - discovery-service
        - config-service
      environment:
        server.port: 8081
        eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka
  user-service:
      image: "lruchandani/user-service:${TAG}"
      ports:
        - "8082:8082"
      depends_on:
        - discovery-service
        - config-service
      environment:
        server.port: 8082
        eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka
        book.service.db.url: jdbc:mysql://10.0.75.1:3306/library?useSSL=false&allowPublicKeyRetrieval=true
  notification-service:
      image: "lruchandani/notification-service:${TAG}"
      ports:
        - "8083:8083"
      depends_on:
        - discovery-service
        - config-service
      environment:
        server.port: 8083
        eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka
  zuul-service:
    image: "lruchandani/zuul-service:${TAG}"
    ports:
      - "8084:8084"
    depends_on:
      - discovery-service
      - config-service
    environment:
      server.port: 8084
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka